import type { MetadataRoute } from "next";
import { CURATED_ITINERARY_TEMPLATE_SLUGS } from "@/lib/itinerary/curated-itinerary-templates";
import { siteUrl } from "@/lib/site";

const STATIC_PATHS = [
  "/",
  "/start-here",
  "/tourists",
  "/residents",
  "/residents/open-bank-account-japan",
  "/residents/japan-bank-holidays-business-hours-guide",
  "/residents/japan-banking-apps-guide",
  "/residents/japan-credit-cards",
  "/residents/japan-mobile-payment-guide",
  "/residents/japan-receipts-points-membership-cards-guide",
  "/residents/send-money-from-japan",
  "/residents/sim-card-japan-residents",
  "/residents/pay-bills-japan",
  "/residents/japan-utilities-setup",
  "/residents/japan-bank-transfers-furikomi",
  "/residents/japan-air-conditioner-guide",
  "/residents/japan-weather-living-guide",
  "/residents/japan-micro-seasons-guide",
  "/residents/japan-seasonal-home-products-guide",
  "/residents/japan-household-items",
  "/residents/ic-card-japan",
  "/residents/renting-apartment-japan",
  "/residents/japan-shared-house-guide",
  "/residents/japan-apartment-viewing-guide",
  "/residents/japan-room-measurements",
  "/residents/japan-neighborhood-guide",
  "/residents/japan-local-neighborhood-shops-guide",
  "/residents/japan-guarantor-system",
  "/residents/japan-furniture-appliances",
  "/residents/japan-secondhand-shopping-guide",
  "/residents/japan-100yen-shop-guide",
  "/residents/japan-health-insurance",
  "/residents/japan-healthcare-costs",
  "/residents/japan-pension-system",
  "/residents/japan-salary-system",
  "/residents/japan-work-contracts",
  "/residents/japan-residence-registration",
  "/residents/japan-renewing-visa-guide",
  "/residents/japan-my-number-card",
  "/residents/japan-taxes-guide",
  "/residents/japan-city-hall-guide",
  "/residents/japan-emergency-guide",
  "/residents/japan-school-system",
  "/residents/japan-garbage-rules",
  "/residents/japan-trash-recycling-guide",
  "/residents/japan-address-system",
  "/residents/japan-driving-license",
  "/residents/japan-apartment-internet",
  "/residents/japan-bike-rules",
  "/residents/japan-bike-commuting-guide",
  "/residents/japan-station-life-guide",
  "/residents/japan-vending-machine-guide",
  "/residents/japan-waiting-in-line-guide",
  "/residents/japan-lost-and-found-guide",
  "/residents/japan-pet-ownership-guide",
  "/residents/japan-online-shopping-guide",
  "/residents/japan-amazon-rakuten-yahoo",
  "/residents/japan-home-cooking-guide",
  "/residents/japan-microwave-frozen-food-guide",
  "/residents/japan-savings-budgeting-guide",
  "/residents/japan-moving-companies-guide",
  "/residents/japan-holidays-long-weekends-guide",
  "/residents/japan-small-apartment-living-guide",
  "/residents/japan-apartment-lighting-guide",
  "/residents/japan-house-slippers-guide",
  "/residents/japan-balcony-living-guide",
  "/residents/japan-clothing-shopping-guide",
  "/residents/japan-mental-health-adjustment-guide",
  "/residents/japan-gym-fitness-guide",
  "/residents/japan-natural-disasters-home-prep-guide",
  "/residents/japan-public-bath-sauna-guide",
  "/residents/japan-daycare-childcare-guide",
  "/residents/furnished-vs-unfurnished-apartments-in-japan",
  "/residents/apartment-rejections-in-japan",
  "/residents/japan-convenience-services-guide",
  "/residents/japan-noise-neighbor-etiquette-guide",
  "/residents/japan-noise-complaints",
  "/residents/japan-apartment-sounds-guide",
  "/residents/japan-furniture-disposal-guide",
  "/residents/japan-phone-scams-fraud-guide",
  "/residents/japan-seasonal-allergies-guide",
  "/residents/japan-rainy-day-lifestyle-guide",
  "/residents/japan-first-winter",
  "/residents/japan-package-delivery-guide",
  "/residents/japan-official-mail-guide",
  "/residents/japan-household-paperwork-guide",
  "/residents/japan-household-cleaning-guide",
  "/residents/clinics-vs-hospitals-in-japan",
  "/residents/japan-moving-out-guide",
  "/residents/japan-mobile-phone-plans",
  "/residents/japan-living-cost",
  "/residents/japan-resident-tax",
  "/residents/garbage-separation-japan",
  "/residents/japan-mistakes-new-residents",
  "/residents/japan-grocery-shopping-guide",
  "/residents/japan-beginner-grocery-list",
  "/residents/japan-self-checkout-guide",
  "/residents/japan-drugstore-lifestyle-guide",
  "/residents/japan-seasonal-food-guide",
  "/residents/japan-weekend-routine-guide",
  "/residents/japan-bank-account",
  "/residents/part-time-jobs-japan",
  "/residents/japan-job-hunting-guide",
  "/residents/japan-work-culture-guide",
  "/residents/japan-time-management-lifestyle-guide",
  "/residents/japan-morning-routine-guide",
  "/residents/japan-night-routine-guide",
  "/residents/japan-language-learning-guide",
  "/residents/japan-social-life-guide",
  "/residents/japan-customer-service-culture-guide",
  "/resources/moving-to-japan-checklist",
  "/tools",
  "/faq",
  "/guides/start-here-japan",
  "/guides/sim-card-japan",
  "/guides/japan-public-wifi",
  "/guides/do-you-need-sim-japan",
  "/guides/esim-vs-pocket-wifi-japan",
  "/guides/airalo-vs-ubigi-japan",
  "/guides/japan-airport-to-city",
  "/guides/japan-luggage-shipping",
  "/guides/japan-coin-lockers",
  "/guides/japan-post-office-guide",
  "/guides/japan-airport-first-steps",
  "/guides/japan-jetlag-survival",
  "/guides/japan-transportation",
  "/guides/japan-budget-breakdown",
  "/tools/japan-trip-budget-calculator",
  "/tools/japan-itinerary-planner",
  "/tools/japan-packing-generator",
  "/tools/can-i-bring-this-to-japan",
  "/tools/japanese-address-formatter",
  "/tools/japan-monthly-cost-calculator",
  "/guides/japan-tax-free-shopping",
  "/guides/japan-anime-shopping-guide",
  "/guides/japan-convenience-store-guide",
  "/guides/japan-familymart-lawson-7eleven-comparison",
  "/guides/japan-conbini-food-guide",
  "/guides/japan-vending-machines",
  "/guides/japan-drugstore-guide",
  "/guides/narita-to-tokyo",
  "/guides/haneda-to-tokyo",
  "/guides/japan-trains",
  "/guides/jr-pass-worth-it",
  "/guides/shinkansen-guide",
  "/guides/suica-vs-pasmo",
  "/guides/suica-pasmo-guide",
  "/guides/japan-train-mistakes",
  "/guides/japan-tourist-mistakes",
  "/guides/japan-mistakes-first-time-visitors",
  "/guides/japan-money-mistakes",
  "/guides/japan-cultural-mistakes",
  "/guides/japan-escalator-rules",
  "/guides/japan-onsen-guide",
  "/guides/japan-nightlife-guide",
  "/guides/japan-travel-insurance",
  "/guides/japan-apps-guide",
  "/guides/using-google-maps-in-japan",
  "/guides/where-to-stay-tokyo",
  "/guides/where-to-stay-kyoto",
  "/guides/where-to-stay-osaka",
  "/guides/best-area-tokyo-first-time",
  "/guides/shinjuku-vs-shibuya",
  "/guides/where-to-stay-japan",
  "/guides/japan-hotel-room-size",
  "/guides/japan-itinerary",
  "/guides/japan-travel-fatigue",
  "/guides/japan-packing-list",
  "/guides/japan-laundry-guide",
  "/guides/japan-restaurant-guide",
  "/guides/japan-food-allergy-guide",
  "/guides/japan-breakfast-cafe-guide",
  "/guides/how-to-use-japanese-toilets",
  "/guides/japan-weather-by-month",
  "/guides/japan-rainy-season-guide",
  "/guides/getting-around-japan",
  "/guides/money-payments-japan",
  "/guides/japan-cash-vs-card",
  "/guides/japan-cash-withdrawal-guide",
];

const TEMPLATE_PATHS = [
  "/itinerary-templates",
  ...CURATED_ITINERARY_TEMPLATE_SLUGS.map(
    (slug) => `/itinerary-templates/${slug}`,
  ),
];

export default function sitemap(): MetadataRoute.Sitemap {
  const base = siteUrl();
  const now = new Date();
  return [...STATIC_PATHS, ...TEMPLATE_PATHS].map((path) => ({
    url: `${base}${path}`,
    lastModified: now,
    changeFrequency: path === "/" ? "weekly" : "monthly",
    priority:
      path === "/"
        ? 1
        : path === "/tools"
          ? 0.8
          : path.startsWith("/guides/")
            ? 0.8
            : path.startsWith("/tools/")
              ? 0.75
              : path.startsWith("/itinerary-templates")
                ? 0.72
                : 0.7,
  }));
}
