import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/site";

const STATIC_PATHS = [
  "/",
  "/start-here",
  "/tourists",
  "/residents",
  "/residents/open-bank-account-japan",
  "/residents/japan-credit-cards",
  "/residents/japan-mobile-payment-guide",
  "/residents/send-money-from-japan",
  "/residents/sim-card-japan-residents",
  "/residents/pay-bills-japan",
  "/residents/japan-utilities-guide",
  "/residents/ic-card-japan",
  "/residents/renting-apartment-japan",
  "/residents/japan-guarantor-system",
  "/residents/japan-furniture-appliances",
  "/residents/japan-secondhand-shopping-guide",
  "/residents/japan-health-insurance",
  "/residents/japan-pension-system",
  "/residents/japan-residence-registration",
  "/residents/japan-renewing-visa-guide",
  "/residents/japan-my-number-card",
  "/residents/japan-taxes-guide",
  "/residents/japan-city-hall-guide",
  "/residents/japan-emergency-guide",
  "/residents/japan-school-system",
  "/residents/japan-garbage-rules",
  "/residents/japan-address-system",
  "/residents/japan-driving-license",
  "/residents/japan-internet-setup",
  "/residents/japan-bike-rules",
  "/residents/japan-clinics-hospitals",
  "/residents/japan-moving-out-guide",
  "/residents/japan-phone-plans",
  "/residents/japan-living-cost",
  "/residents/japan-grocery-shopping-guide",
  "/residents/japan-bank-account",
  "/residents/part-time-jobs-japan",
  "/residents/japan-job-hunting-guide",
  "/residents/japan-work-culture-guide",
  "/resources/moving-to-japan-checklist",
  "/guides/start-here-japan",
  "/guides/sim-card-japan",
  "/guides/do-you-need-sim-japan",
  "/guides/esim-vs-pocket-wifi-japan",
  "/guides/airalo-vs-ubigi-japan",
  "/guides/japan-airport-to-city",
  "/guides/japan-luggage-shipping",
  "/guides/japan-coin-lockers",
  "/guides/japan-post-office-guide",
  "/guides/japan-airport-first-steps",
  "/guides/japan-transportation",
  "/guides/japan-budget-breakdown",
  "/guides/japan-tax-free-shopping",
  "/guides/japan-anime-shopping-guide",
  "/guides/japan-convenience-store-guide",
  "/guides/japan-conbini-food-guide",
  "/guides/japan-vending-machines",
  "/guides/japan-drugstore-guide",
  "/guides/narita-to-tokyo",
  "/guides/haneda-to-tokyo",
  "/guides/japan-trains",
  "/guides/jr-pass-worth-it",
  "/guides/shinkansen-guide",
  "/guides/suica-vs-pasmo",
  "/guides/suica-pasmo-guide",
  "/guides/japan-train-mistakes",
  "/guides/japan-tourist-mistakes",
  "/guides/japan-cultural-mistakes",
  "/guides/japan-onsen-guide",
  "/guides/japan-nightlife-guide",
  "/guides/japan-travel-insurance",
  "/guides/japan-apps-guide",
  "/guides/where-to-stay-tokyo",
  "/guides/where-to-stay-kyoto",
  "/guides/where-to-stay-osaka",
  "/guides/best-area-tokyo-first-time",
  "/guides/shinjuku-vs-shibuya",
  "/guides/where-to-stay-japan",
  "/guides/japan-itinerary",
  "/guides/japan-packing-list",
  "/guides/japan-restaurant-guide",
  "/guides/japan-breakfast-cafe-guide",
  "/guides/how-to-use-japanese-toilets",
  "/guides/japan-weather-by-month",
  "/guides/japan-rainy-season-guide",
  "/guides/getting-around-japan",
  "/guides/money-payments-japan",
  "/guides/japan-cash-vs-card",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const base = siteUrl();
  const now = new Date();
  return STATIC_PATHS.map((path) => ({
    url: `${base}${path}`,
    lastModified: now,
    changeFrequency: path === "/" ? "weekly" : "monthly",
    priority: path === "/" ? 1 : path.startsWith("/guides/") ? 0.8 : 0.7,
  }));
}
