/** Hub section labels for resident guides (matches app/residents/page.tsx). */
export const RESIDENT_GUIDE_SECTIONS = [
  {
    label: "Start Here",
    slugs: [
      "japan-residence-registration",
      "japan-my-number-card",
      "japan-city-hall-guide",
      "japan-renewing-visa-guide",
      "japan-address-system",
      "japan-official-mail-guide",
      "japan-bank-transfers-furikomi",
      "japan-household-paperwork-guide",
      "open-bank-account-japan",
      "japan-bank-holidays-business-hours-guide",
      "japan-banking-apps-guide",
      "sim-card-japan-residents",
      "japan-apartment-internet",
      "japan-mobile-phone-plans",
      "japan-bank-account",
      "japan-credit-cards",
      "japan-mobile-payment-guide",
      "japan-receipts-points-membership-cards-guide",
      "japan-phone-scams-fraud-guide",
      "send-money-from-japan",
      "ic-card-japan",
      "japan-driving-license",
    ],
  },
  {
    label: "Families",
    slugs: [
      "japan-school-system",
      "japan-daycare-childcare-guide",
      "japan-furniture-appliances",
      "japan-secondhand-shopping-guide",
      "japan-100yen-shop-guide",
      "japan-clothing-shopping-guide",
      "japan-pet-ownership-guide",
    ],
  },
  {
    label: "Daily Life",
    slugs: [
      "japan-living-cost",
      "japan-savings-budgeting-guide",
      "japan-grocery-shopping-guide",
      "japan-beginner-grocery-list",
      "japan-self-checkout-guide",
      "japan-drugstore-lifestyle-guide",
      "japan-seasonal-food-guide",
      "japan-weekend-routine-guide",
      "japan-home-cooking-guide",
      "japan-microwave-frozen-food-guide",
      "japan-online-shopping-guide",
      "japan-amazon-rakuten-yahoo",
      "japan-package-delivery-guide",
      "pay-bills-japan",
      "japan-convenience-services-guide",
      "japan-utilities-setup",
      "japan-air-conditioner-guide",
      "japan-weather-living-guide",
      "japan-micro-seasons-guide",
      "japan-seasonal-home-products-guide",
      "japan-household-items",
      "japan-household-cleaning-guide",
      "japan-seasonal-allergies-guide",
      "japan-rainy-day-lifestyle-guide",
      "japan-first-winter",
      "japan-holidays-long-weekends-guide",
      "japan-social-life-guide",
      "japan-customer-service-culture-guide",
      "japan-mental-health-adjustment-guide",
      "japan-garbage-rules",
      "japan-trash-recycling-guide",
      "japan-furniture-disposal-guide",
      "japan-health-insurance",
      "japan-healthcare-costs",
      "clinics-vs-hospitals-in-japan",
      "japan-emergency-guide",
      "japan-natural-disasters-home-prep-guide",
      "japan-pension-system",
      "japan-bike-rules",
      "japan-bike-commuting-guide",
      "japan-station-life-guide",
      "japan-vending-machine-guide",
      "japan-waiting-in-line-guide",
      "japan-lost-and-found-guide",
      "japan-gym-fitness-guide",
      "japan-public-bath-sauna-guide",
    ],
  },
  {
    label: "Work and Systems",
    slugs: [
      "part-time-jobs-japan",
      "japan-job-hunting-guide",
      "japan-salary-system",
      "japan-work-contracts",
      "japan-work-culture-guide",
      "japan-time-management-lifestyle-guide",
      "japan-morning-routine-guide",
      "japan-night-routine-guide",
      "japan-language-learning-guide",
      "renting-apartment-japan",
      "japan-shared-house-guide",
      "japan-apartment-viewing-guide",
      "japan-room-measurements",
      "furnished-vs-unfurnished-apartments-in-japan",
      "apartment-rejections-in-japan",
      "japan-small-apartment-living-guide",
      "japan-apartment-lighting-guide",
      "japan-house-slippers-guide",
      "japan-balcony-living-guide",
      "japan-noise-neighbor-etiquette-guide",
      "japan-noise-complaints",
      "japan-apartment-sounds-guide",
      "japan-neighborhood-guide",
      "japan-local-neighborhood-shops-guide",
      "japan-guarantor-system",
      "japan-moving-out-guide",
      "japan-moving-companies-guide",
      "japan-taxes-guide",
    ],
  },
] as const;

export const RESIDENT_SLUG_SECTION: Record<string, string> =
  Object.fromEntries(
    RESIDENT_GUIDE_SECTIONS.flatMap(({ label, slugs }) =>
      slugs.map((slug) => [slug, label]),
    ),
  );
